#!/bin/bash

echo "============================="
echo "DynamoDB is running?"
ps a | grep --color=auto DynamoDB

echo "============================="
echo "List of local DynamoDB tables"
aws --endpoint-url http://localhost:8000 dynamodb list-tables

echo "============================="
echo "List of items in Events table"
aws --endpoint-url http://localhost:8000 dynamodb scan --table-name Events

#echo "============================="
#echo "List of items in Users table"
#aws --endpoint-url http://localhost:8000 dynamodb scan --table-name Users

echo "============================="
echo "Node.js is running?"
ps a | grep --color=auto "node -e"

echo "============================="
echo "endpoint /graphql query event 1 works?"
echo "Request: "$JSON_BODY
JSON_BODY='{"query":"{event(eventId:\"1\"){placeId}}"}'
curl localhost:3001/graphql -XPOST -d $JSON_BODY
echo ""

echo "============================="
echo "endpoint /graphql mutation createEvent works?"
JSON_BODY='{"query":"mutation{createEvent(placeId:\"hi\",eventName:\"bye\"){eventId}}"}'
echo "Request: "$JSON_BODY
curl localhost:3001/graphql -XPOST -d $JSON_BODY
echo ""

echo "============================="
echo "endpoint /graphql mutation updateEventUser works?"
JSON_BODY='{"query":"mutation{updateEventUser(eventId:\"1\",userName:\"Seob\",duration:13){userName}}"}'
echo "Request: "$JSON_BODY
curl localhost:3001/graphql -XPOST -d $JSON_BODY
echo ""

echo "============================="
echo "endpoint /graphql query eventUsers of 1 works?"
JSON_BODY='{"query":"{event(eventId:\"1\"){eventUsers{userName,duration}}}"}'
echo "Request: "$JSON_BODY
curl localhost:3001/graphql -XPOST -d $JSON_BODY
echo ""
echo "============================="
