#!/bin/bash
echo "============================="
echo "DynamoDB is running?"
ps a | grep --color=auto DynamoDB
echo "============================="
echo "List of local DynamoDB tables"
aws --endpoint-url http://localhost:8000 dynamodb list-tables
echo "============================="
echo "List of items in Events table"
aws --endpoint-url http://localhost:8000 dynamodb scan --table-name Events
echo "============================="
echo "List of items in EventUsers table"
aws --endpoint-url http://localhost:8000 dynamodb scan --table-name EventUsers
echo "============================="
echo "Node.js is running?"
ps a | grep --color=auto "node -e"
echo "============================="
echo "endpoint GET /api/events/1 works?"
curl localhost:3001/api/events/1
echo ""
echo "============================="
