AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ApiGateway:
    Properties:
      DefinitionBody:
        info:
          title: Cobyo-API
          version: 1.0.0
        paths:
          /graphql:
            options:
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Credentials:
                      type: string
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
              x-amazon-apigateway-integration:
                requestTemplates:
                  application/json: '{''statusCode'':200}'
                responses:
                  default:
                    responseParameters:
                      method.response.header.Access-Control-Allow-Credentials: '''true'''
                      method.response.header.Access-Control-Allow-Headers: '''content-type'''
                      method.response.header.Access-Control-Allow-Methods: '''OPTIONS,POST'''
                      method.response.header.Access-Control-Allow-Origin: '''https://cobyo.me'''
                    statusCode: 200
                type: mock
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                responses: {}
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Lambda.Arn}/invocations
        swagger: 2.0
      StageName: prod
    Type: AWS::Serverless::Api
  Lambda:
    Properties:
      CodeUri: s3://cobyo.backend/lambda.zip
      Environment:
        Variables:
          ALLOW_ORIGIN: https://cobyo.me
          DYNAMODB_ENDPOINT:
            Fn::Sub: https://dynamodb.${AWS::Region}.amazonaws.com
          TABLE_NAME:
            Ref: Table
          SLACK_WEBHOOK_PATH: /services/TD40HQR7F/BDK27A1SN/F3dsvY0guxCaJAMR1dTjYcOH
      Events:
        ApiProxy:
          Properties:
            Method: POST
            Path: /graphql
            RestApiId:
              Ref: ApiGateway
          Type: Api
      Handler: index.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: Table
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  LambdaPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: Lambda
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*
    Type: AWS::Lambda::Permission
  Mapping:
    DependsOn: ApiGatewayprodStage
    Properties:
      DomainName: api.cobyo.me
      RestApiId:
        Ref: ApiGateway
      Stage: prod
    Type: AWS::ApiGateway::BasePathMapping
  Table:
    Properties:
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: groupId
        AttributeType: S
      GlobalSecondaryIndexes:
      - IndexName: Group
        KeySchema:
        - AttributeName: groupId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: groupId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Table
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
