#!/bin/bash

export NPM_INSTALL='graphql fs uuid https web-push'
export NPM_INSTALL_LOCAL_ONLY='express aws-sdk'
export API_PATH=/graphql

# Prod Server test purpose
export PROD_API_SERVER=https://api.cobyo.me

# Dev Environments used in index.js
export DEV_API_SERVER=http://localhost
export DEV_API_PORT=3001
export AWS_REGION=us-east-1
export ALLOW_ORIGIN=$DEV_API_SERVER:3000
export DYNAMODB_PORT=9520
export DYNAMODB_ENDPOINT=$DEV_API_SERVER:$DYNAMODB_PORT
export TABLE_NAME=Table

# Dynamodb Default Event
export DEFAULT_EVENT='{"userId":{"S":"Event-1"},"groupId":{"S":"Event-1"},"code":{"S":"1"},"place":{"M":{"googlePlaceId":{"S":"ChIJ7VHBwnZ644kRKRWP5Qe27v4"}}},"eventName":{"S":"Royale"}}'

function test_post {
  ADDSPACE1=${2//\{/ \{ }
  ADDSPACE2=${ADDSPACE1//\}/ \} }
  ADDSPACE3=${ADDSPACE2//\,/\, }
  echo "Request:"$ADDSPACE3
  curl $GRAPHQL_ENDPOINT -XPOST -H "Cookie: SESSION_ID=$SESSION_ID" -d '{"query":"'$1'"}' 2>/dev/null | python -mjson.tool
  echo ""
  echo "==========================================================================="
}

function test_smoke {
  export GRAPHQL_ENDPOINT=$1$API_PATH
  echo "==========================================================================="
  echo "Check POST with wrong endpoint"
  curl -i $1/random -XPOST 2>/dev/null
  echo "==========================================================================="
  echo "Check OPTIONS with no data"
  curl -i $GRAPHQL_ENDPOINT -XOPTIONS 2>/dev/null
  echo "==========================================================================="
  echo "Check POST with no data"
  curl -i $GRAPHQL_ENDPOINT -XPOST 2>/dev/null
  echo ""
  echo "==========================================================================="
  echo "Check POST with empty data sets SESSION_ID"
  export SESSION_ID=`curl -i $GRAPHQL_ENDPOINT -XPOST -d '{}' 2>/dev/null | grep -i set-cookie | cut -d'=' -f2 | cut -d';' -f1`
  echo ""
  echo "SESSION_ID=$SESSION_ID"
  echo "==========================================================================="
  test_post '{me{name}}'
  test_post '{event(code:\"1\"){code,name,endedTime,scheduledTime,place{googlePlaceId,address,latitude,longitude,photoUrl},me{duration,updatedTime,travelMode,hasLeft,user{name}},numAttendees,eventUsers{duration,updatedTime,travelMode,hasLeft,user{name}},notifications{message,createdTime,reactions{emoji,user{name}}}}}'
  test_post 'mutation{editMe(user:{name:\"Jay2\"}){name}}'
  test_post 'mutation{createEvent(event:{place:{googlePlaceId:\"hi\"}}){code,name,endedTime,scheduledTime,place{googlePlaceId,address,latitude,longitude,photoUrl}}}'
  test_post 'mutation{joinEvent(code:\"1\"){user{name},duration,updatedTime,travelMode,hasLeft}}'
  test_post 'mutation{editEvent(code:\"1\",event:{place:{address:\"hi\"},name:\"royale2\",scheduledTime:\"123\"}){code,name,endedTime,scheduledTime,place{address}}}'
  test_post 'mutation{updateEventUser(eventCode:\"1\",eventUser:{duration:250,updatedTime:\"'$(date +%s)'\",travelMode:\"DRIVING\",hasLeft:true}){user{name},duration,updatedTime,travelMode,hasLeft}}'
  test_post 'mutation{endEvent(code:\"1\"){endedTime}}'
  test_post '{me{name}}'
  test_post '{event(code:\"1\"){code,name,endedTime,scheduledTime,place{googlePlaceId,address,latitude,longitude,photoUrl},me{duration,updatedTime,travelMode,hasLeft,user{name}},numAttendees,eventUsers{duration,updatedTime,travelMode,hasLeft,user{name}},notifications{message,createdTime,reactions{emoji,user{name}}}}}'
  #test_post 'mutation{createReaction(eventCode:\"1\",notificationIndex:0,reaction:{emoji:\"Hi\"}){user{name},emoji}}'
  #test_post 'mutation{deleteReaction(eventCode:\"1\",notificationIndex:0,reaction:{emoji:\"Hi\"}){user{name},emoji}}'
}

case $1 in
  "lambda")
    rm -rf node_modules
    echo "Installing node_modules..."
    npm install $NPM_INSTALL &>/dev/null
    echo "Zipping source files..."
    zip -r lambda.zip index.js schema node_modules >/dev/null
    echo "Uploading source package to S3..."
    aws s3 cp lambda.zip s3://cobyo.backend/lambda.zip >/dev/null
    rm -rf lambda.zip node_modules package-lock.json
    eval `aws lambda list-functions | python -c "import json,sys; print \"export LAMBDA_FUNCTION_NAME=%s\" % json.load(sys.stdin)['Functions'][0]['FunctionName']"`
    echo "Updating lambda function code for $LAMBDA_FUNCTION_NAME..."
    aws lambda update-function-code --s3-bucket cobyo.backend --s3-key lambda.zip --function-name $LAMBDA_FUNCTION_NAME
    ;;

  "initdb")
    aws dynamodb put-item --table-name $TABLE_NAME --item $DEFAULT_EVENT
    ;;

  "dev")
    rm -rf node_modules
    npm install $NPM_INSTALL_LOCAL_ONLY $NPM_INSTALL &> /dev/null
    rm -f package-lock.json
    java -jar DynamoDBLocal.jar -sharedDb -inMemory -port $DYNAMODB_PORT >/dev/null &
    PID=$!
    trap "kill -TERM $PID" TERM INT
    aws --endpoint-url $DYNAMODB_ENDPOINT dynamodb create-table --table-name $TABLE_NAME --attribute-definitions AttributeName=userId,AttributeType=S AttributeName=groupId,AttributeType=S --key-schema AttributeName=userId,KeyType=HASH AttributeName=groupId,KeyType=RANGE --global-secondary-index IndexName=Group,KeySchema='[{AttributeName=groupId,KeyType=HASH},{AttributeName=userId,KeyType=RANGE}]',Projection='{ProjectionType=ALL}',ProvisionedThroughput='{ReadCapacityUnits=1,WriteCapacityUnits=1}' --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 >/dev/null
    aws --endpoint-url $DYNAMODB_ENDPOINT dynamodb put-item --table-name $TABLE_NAME --item $DEFAULT_EVENT
    node dev_server.js
    ;;

  "test-dev")
    test_smoke $DEV_API_SERVER:$DEV_API_PORT
    ;;

  "test-prod")
    test_smoke $PROD_API_SERVER
    ;;

  *)
    echo "Usage: ./run [command]"
    echo ""
    echo "< Production Tools >"
    echo "initdb    initializes production DB state"
    echo "lambda    deploys lambda"
    echo "test-prod runs smoke-test on production api server"
    echo ""
    echo "< Development Tools >"
    echo "dev       runs local backend"
    echo "test-dev  runs smoke-test on development api server"
    ;;
esac

